# configuration for ELP USB camera stream in Python-OpenCV
---
window_name: "window"

camera_id: 2

resolution:
  - 1280
  - 720

fps: 120

brightness: 10

contrast: 15

saturation: 75

frame_height: 
  - 0
  - 650

frame_width:
  - 200
  - 1100

ball_radius:
  - 10
  - 20

median_offset: 2

magnitude_scalar: 100

search_area: 60

text_tl:
  - 40
  - 40

text_tr:
  - 550
  - 40

text_spacing: 40

text_size: 1

# corner offsets
# (tl_offset, tr_offset, bl_offset, br_offset)
# only setup for 1080p currently
offsets:
  - 100
  - 100
  - 80
  - 60
