# configuration for ELP USB camera stream in Python-OpenCV
---
window_name: "window"

camera_id: 2

resolution:
  - 1920
  - 1080

fps: 60

brightness: 10

contrast: 15

saturation: 75

frame_height:
  - 80
  - 1080

frame_width:
  - 360
  - 1600

ball_radius:
  - 20
  - 28
